# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: "0 * * * *"
  displayName: Daily midnight build
  branches:
    include:
    - main

pool:
  vmImage: ubuntu-latest

steps:
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber-brief7-gs'
    namespace: 'brief7-gs'
    command: 'get'
    arguments: 'deployments'
    outputFormat: 'json'
  name: "kube"

- task: CmdLine@2
  inputs:
    script: |
      versionnew=$((curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')| sed 's/^.//;s/.$//')
      echo $versionnew
      echo "##vso[task.setvariable variable=vernew;]$versionnew"
      cd /home/vsts
      git clone https://github.com/simplon-gabrielsarais/Brief-7.git
      cd Brief-7
      ls
- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber-brief7-gs'
    namespace: 'brief7-gs'
    command: 'apply'
    useConfigurationFile: true
    configuration: '/Brief-7/kube_brief6'
    arguments: '-f'
    secretType: 'generic'

- task: CmdLine@2
  inputs:
    script: |
      echo $(vernew)
      echo $KUBE_KUBECTLOUTPUT