# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber-brief7-gs'
    namespace: 'brief7-gs'
    command: 'get'
    arguments: 'deployments'
  name: "kube"
- task: CmdLine@2
  inputs:
    script: |
      cat /home/vsts/version/version.vote
      mkdir /home/vsts/version
      mkdir /home/vsts/git
      pwd
      TESTVAR=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      echo "$TESTVAR"|sed 's/^.//;s/.$//' >/home/vsts/version/version.vote
      cat /home/vsts/version/version.vote
      version=$(cat /home/vsts/version/version.vote)
      echo $version
      echo "##vso[task.setvariable variable=test;]$version"

- task: DownloadGitHubRelease@0
  inputs:
    connection: 'github.com_simplon-gabrielsarais'
    userRepository: 'simplon-gabrielsarais/Brief-7'
    defaultVersionType: 'Latest'
    itemPattern: '*.zip'
    downloadPath: '/home/vsts/git'

- task: CmdLine@2
  inputs:
    script: |
      cd /home/vsts/git
      ls -a
      cat /home/vsts/version/version.vote
      echo $(test)
      echo $(kube.KubectlOutput)

