# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

schedules:
- cron: "0 0,1,12,18 * * *"
  displayName: Daily midnight build

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Kubernetes@1
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: 'kuber-brief7-gs'
    namespace: 'brief7-gs'
    command: 'get'
    arguments: 'deployments'
    outputFormat: 'json'
  name: "kube"

- task: CmdLine@2
  inputs:
    script: |
      VERSIONNEW=$(curl 'https://hub.docker.com/v2/repositories/simplonasa/azure_voting_app/tags' | jq '."results"[0]["name"]')
      echo "$VERSIONNEW"|sed 's/^.//;s/.$//'
      echo $VERSIONNEW
      echo "##vso[task.setvariable variable=vernew;]$VERSIONNEW"

- task: CmdLine@2
  inputs:
    script: |
      echo $(vernew)
      echo $KUBE_KUBECTLOUTPUT | jq ."apiVersion"